"use strict";
var ip = require('ip');
console.log('ip:' + ip.address());
if (ip.address() == '172.31.18.120') {
    module.exports = {
        PROJECT_NAME: 'brand',
        APP_URL: 'http://52.14.255.158:7171/',
        ADMIN_APP_URL: 'http://52.14.255.158:7272/',
        LIVE_HOST_NAME: 'http://52.14.255.158:7272',
        LIVE_HOST_USER_APP: 'http://52.14.255.158:7272',
        HASH_APP_URL: 'http://52.14.255.158:7171/',
        LOCAL_HOST_NAME: '52.14.255.158:7272',
        LOCAL_HOST_USER_APP: '52.14.255.158:7171',
        LIVE_URL: 'https://52.14.255.158:7272',
        LOCAL_URL: 'https://52.14.255.158:7272',
        USER_LIVE_URL: 'http://52.14.255.158:7171/',
        USER_LOCAL_URL: 'http://52.14.255.158:7171/',
        ADMIN_LIVE_URL: 'http://52.14.255.158:7272/',
        ADMIN_LOCAL_URL: 'http://52.14.255.158:7272/',
        ABOUT_PATH: '/uploads/about/',
        ABOUT_VIEW_PATH: '/about/',
        CLUB_BULK_CSV_UPLOAD_PATH: '/uploads/clubBulkUploadCsv/',  
        BRAND_PATH: '/uploads/brand/',
        BRAND_VIEW_PATH: '/brand/',
        BRAND_VIDEO_PATH: '/uploads/brand/video',
        BRAND_VIDEO_VIEW_PATH: '/brand/video/',
        BRAND_AUDIO_PATH: '/uploads/brand/audio',
        BRAND_AUDIO_VIEW_PATH: '/brand/audio/',
        BRAND_ZIP_PATH: '/uploads/brand/zip/',
        BRAND_ZIP_VIEW_PATH: '/brand/zip/',
        BRAND_CERTIFICATE_PATH: '/uploads/brand/certificate/',
        BRAND_CERTIFICATE_VIEW_PATH: '/brand/certificate/',
        SECRET: '!yO8824AI$6u',
        MAIL_FROM: 'medcheck@oursmartfuture.com',
        MAIL_FROM_MULTIPLE: 'medcheck@oursmartfuture.com',
        ADMIN_MAIL_TO: 'medcheck@oursmartfuture.com', // comma seperated multiple can be added
        IPSTACK_API_KEY: 'ab25d741defc297115d8c9115309a77d',
        PAYPAL_CLIENT_ID: 'AeZu7Ax_73ZZ88R6TSxfR9EjP76C3_hqDx4KrLSLJw6IUP3TpUc6epeNd442dLWOQL3YYXZccBp7M0aQ',
        PAYPAL_SECRET_KEY: 'EDLGO1lDqEQ3Oq_M9naIyWkH70MmTc5UVoxuz3Mo_4TucvgqM7w4q5hNnZowAq_O3_AHFW9vrdSp9w-b',
        PAYPAL_URL: 'https://api-m.sandbox.paypal.com',
        DEBUG: true,
    }
} else {
    module.exports = {
        PROJECT_NAME: 'brand',
        APP_URL: 'http://localhost:7171/',
        ADMIN_APP_URL: 'http://localhost:7272/',
        HASH_APP_URL: 'http://localhost:7171/',
        USER_LIVE_URL: 'http://localhost:7171',
        USER_LOCAL_URL: 'http://localhost:7171',
        ADMIN_LIVE_URL: 'http://localhost:7272',
        ADMIN_LOCAL_URL: 'http://localhost:7272',        
        ABOUT_PATH: '/uploads/about/',
        ABOUT_VIEW_PATH: '/about/',
        BRAND_PATH: '/uploads/brand/',
        BRAND_VIEW_PATH: '/brand/',
        BRAND_VIDEO_PATH: '/uploads/brand/video',
        BRAND_VIDEO_VIEW_PATH: '/brand/video/',
        BRAND_AUDIO_PATH: '/uploads/brand/audio',
        BRAND_AUDIO_VIEW_PATH: '/brand/audio/',
        BRAND_ZIP_PATH: '/uploads/brand/zip/',
        BRAND_ZIP_VIEW_PATH: '/brand/zip/',
        BRAND_CERTIFICATE_PATH: '/uploads/brand/certificate/',
        BRAND_CERTIFICATE_VIEW_PATH: '/brand/certificate/',
        SECRET: '!yO8824AI$6u',
        MAIL_FROM: 'medcheck@oursmartfuture.com',
        MAIL_FROM_MULTIPLE: 'medcheck@oursmartfuture.com',
        ADMIN_MAIL_TO:'medcheck@oursmartfuture.com',
        IPSTACK_API_KEY: 'ab25d741defc297115d8c9115309a77d',
        PAYPAL_CLIENT_ID: 'AeZu7Ax_73ZZ88R6TSxfR9EjP76C3_hqDx4KrLSLJw6IUP3TpUc6epeNd442dLWOQL3YYXZccBp7M0aQ',
        PAYPAL_SECRET_KEY: 'EDLGO1lDqEQ3Oq_M9naIyWkH70MmTc5UVoxuz3Mo_4TucvgqM7w4q5hNnZowAq_O3_AHFW9vrdSp9w-b',
        PAYPAL_URL: 'https://api-m.sandbox.paypal.com',
        DEBUG: true,
    }
}
